---
version: 2
updates:
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
    target-branch: master
    open-pull-requests-limit: 10

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
    target-branch: v7
    open-pull-requests-limit: 10

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
    target-branch: v8
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    target-branch: master
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    target-branch: v7
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    target-branch: v8
    open-pull-requests-limit: 10
